// MLRI LMS — Content Data
window.LMS_DATA = {
  practiceAreas: [
    "Civil Rights", "Housing & Tenant Rights", "Family Law", "Immigration",
    "Criminal Defense", "Public Benefits", "Consumer Law", "Employment Law",
    "Disability Rights", "Elder Law"
  ],

  recentlyUpdated: ["civil-rights-foundations", "housing-eviction-defense", "module-4th-amendment"],

  items: [
    // ── PATHS ───────────────────────────────────────────────────────────
    {
      id: "path-new-attorney",
      type: "path",
      title: "New Legal Aid Attorney Onboarding",
      description: "Everything a first-year legal aid attorney needs to hit the ground running. From your first client intake to your first courtroom appearance — structured, practical, human.",
      practiceArea: "All Practice Areas",
      duration: "12 hr total",
      level: "Foundations",
      courses: 6,
      updated: "2025-04-10",
      isNew: true,
      tags: ["onboarding", "court", "intake", "litigation basics"]
    },
    {
      id: "path-civil-rights",
      type: "path",
      title: "Civil Rights Practitioner",
      description: "A comprehensive path covering constitutional protections, civil rights litigation strategy, and client advocacy for civil rights cases.",
      practiceArea: "Civil Rights",
      duration: "9 hr total",
      level: "Intermediate",
      courses: 4,
      updated: "2025-03-28",
      isNew: false,
      tags: ["civil rights", "constitution", "litigation"]
    },
    {
      id: "path-housing",
      type: "path",
      title: "Housing & Eviction Defense Specialist",
      description: "Master eviction defense, habitability claims, and tenant advocacy from pre-trial motions through appeal.",
      practiceArea: "Housing & Tenant Rights",
      duration: "8 hr total",
      level: "Intermediate",
      courses: 5,
      updated: "2025-04-22",
      isNew: true,
      tags: ["housing", "eviction", "tenant", "habitability"]
    },
    {
      id: "path-litigation",
      type: "path",
      title: "Litigation Support Fundamentals",
      description: "Build your courtroom confidence. Objections, motions practice, witness examination, and courtroom procedure for legal aid attorneys.",
      practiceArea: "All Practice Areas",
      duration: "7 hr total",
      level: "Foundations",
      courses: 3,
      updated: "2025-02-14",
      isNew: false,
      tags: ["litigation", "court", "objections", "motions"]
    },

    // ── COURSES ─────────────────────────────────────────────────────────
    {
      id: "civil-rights-foundations",
      type: "course",
      title: "Civil Rights Law — Foundations",
      description: "Core constitutional protections every legal aid attorney must know. Covers 1st, 4th, and 14th Amendments with practical application to client cases.",
      practiceArea: "Civil Rights",
      duration: "45 min",
      level: "Foundations",
      modules: 4,
      updated: "2025-04-15",
      isNew: true,
      tags: ["civil rights", "constitution", "amendments", "foundations"],
      brightspaceUrl: "#brightspace/civil-rights-foundations"
    },
    {
      id: "housing-eviction-defense",
      type: "course",
      title: "Eviction Defense: From Notice to Trial",
      description: "Step-by-step guidance through the eviction defense process. Filing answers, asserting defenses, negotiating with landlords, and winning at trial.",
      practiceArea: "Housing & Tenant Rights",
      duration: "2 hr 30 min",
      level: "Intermediate",
      modules: 6,
      updated: "2025-04-20",
      isNew: true,
      tags: ["eviction", "housing", "tenant", "trial", "defenses"],
      brightspaceUrl: "#brightspace/eviction-defense"
    },
    {
      id: "court-procedure-basics",
      type: "course",
      title: "Court Procedure & Courtroom Basics",
      description: "How to actually behave and advocate in a courtroom. Covers filing, appearances, motions practice, and what to do when you don't know what to do.",
      practiceArea: "All Practice Areas",
      duration: "1 hr 30 min",
      level: "Foundations",
      modules: 5,
      updated: "2025-01-30",
      isNew: false,
      tags: ["court", "procedure", "motions", "appearances", "litigation"],
      brightspaceUrl: "#brightspace/court-procedure"
    },
    {
      id: "legal-research-writing",
      type: "course",
      title: "Legal Research & Writing",
      description: "From Westlaw to a winning brief. Research strategies, case citation, memo writing, and persuasive argument structure.",
      practiceArea: "All Practice Areas",
      duration: "2 hr",
      level: "Foundations",
      modules: 5,
      updated: "2025-02-10",
      isNew: false,
      tags: ["research", "writing", "brief", "westlaw", "citations"],
      brightspaceUrl: "#brightspace/legal-research"
    },
    {
      id: "investigative-techniques",
      type: "course",
      title: "Investigative Techniques for Legal Aid",
      description: "How to build your case before you get to court. Client interviews, document gathering, chain of custody, and working with investigators.",
      practiceArea: "All Practice Areas",
      duration: "3 hr",
      level: "Intermediate",
      modules: 7,
      updated: "2025-03-05",
      isNew: false,
      tags: ["investigation", "interview", "evidence", "client"],
      brightspaceUrl: "#brightspace/investigative-techniques"
    },
    {
      id: "family-law-basics",
      type: "course",
      title: "Family Law for Legal Aid Attorneys",
      description: "Divorce, custody, child support, and domestic violence protective orders. Practical guidance for navigating emotionally complex family law cases.",
      practiceArea: "Family Law",
      duration: "2 hr 15 min",
      level: "Foundations",
      modules: 6,
      updated: "2025-03-18",
      isNew: false,
      tags: ["family", "custody", "divorce", "domestic violence", "protective order"],
      brightspaceUrl: "#brightspace/family-law"
    },
    {
      id: "immigration-removal-defense",
      type: "course",
      title: "Immigration Removal Defense",
      description: "Essentials of removal defense: hearing prep, bond motions, asylum basics, and coordination with immigration specialists.",
      practiceArea: "Immigration",
      duration: "2 hr 45 min",
      level: "Intermediate",
      modules: 5,
      updated: "2025-04-18",
      isNew: true,
      tags: ["immigration", "removal", "asylum", "bonds", "deportation"],
      brightspaceUrl: "#brightspace/immigration-removal"
    },
    {
      id: "evidence-discovery",
      type: "course",
      title: "Evidence & Discovery",
      description: "Rules of evidence, discovery requests, depositions, and how to handle what opposing counsel throws at you.",
      practiceArea: "All Practice Areas",
      duration: "1 hr 30 min",
      level: "Intermediate",
      modules: 4,
      updated: "2024-12-10",
      isNew: false,
      tags: ["evidence", "discovery", "depositions", "objections"],
      brightspaceUrl: "#brightspace/evidence"
    },
    {
      id: "client-intake",
      type: "course",
      title: "Client Intake & Case Assessment",
      description: "Your first conversation with a client sets the tone for everything. Trauma-informed intake, eligibility screening, and setting realistic expectations.",
      practiceArea: "All Practice Areas",
      duration: "1 hr",
      level: "Foundations",
      modules: 3,
      updated: "2025-01-12",
      isNew: false,
      tags: ["intake", "client", "trauma-informed", "screening", "assessment"],
      brightspaceUrl: "#brightspace/client-intake"
    },
    {
      id: "public-benefits",
      type: "course",
      title: "Public Benefits: SNAP, SSI & Medicaid",
      description: "Navigating public benefits appeals and fair hearing procedures. Covers SNAP, SSI disability appeals, and Medicaid eligibility disputes.",
      practiceArea: "Public Benefits",
      duration: "1 hr 45 min",
      level: "Foundations",
      modules: 4,
      updated: "2025-02-28",
      isNew: false,
      tags: ["benefits", "SNAP", "SSI", "Medicaid", "appeals", "hearing"],
      brightspaceUrl: "#brightspace/public-benefits"
    },

    // ── MODULES ─────────────────────────────────────────────────────────
    {
      id: "module-4th-amendment",
      type: "module",
      title: "The Fourth Amendment Explained",
      parentCourse: "Civil Rights Law — Foundations",
      parentCourseId: "civil-rights-foundations",
      description: "Search and seizure law from Terry stops to digital privacy. What your clients need to know about their 4th Amendment rights.",
      practiceArea: "Civil Rights",
      duration: "20 min",
      updated: "2025-04-15",
      isNew: true,
      tags: ["4th amendment", "search", "seizure", "police", "privacy"],
      brightspaceUrl: "#brightspace/civil-rights-foundations/4th-amendment"
    },
    {
      id: "module-reading-citations",
      type: "module",
      title: "Reading Case Citations",
      parentCourse: "Legal Research & Writing",
      parentCourseId: "legal-research-writing",
      description: "Decode any case citation. Federal reporters, state court abbreviations, parallel citations, and Bluebook basics.",
      practiceArea: "All Practice Areas",
      duration: "30 min",
      updated: "2025-02-10",
      isNew: false,
      tags: ["citations", "bluebook", "research", "case law"],
      brightspaceUrl: "#brightspace/legal-research/citations"
    },
    {
      id: "module-interview-best-practices",
      type: "module",
      title: "Client Interview Best Practices",
      parentCourse: "Investigative Techniques for Legal Aid",
      parentCourseId: "investigative-techniques",
      description: "Trauma-informed interviewing techniques. How to build trust, get complete facts, and document client stories accurately.",
      practiceArea: "All Practice Areas",
      duration: "45 min",
      updated: "2025-03-05",
      isNew: false,
      tags: ["interview", "client", "trauma", "intake"],
      brightspaceUrl: "#brightspace/investigative-techniques/interview"
    },
    {
      id: "module-chain-of-custody",
      type: "module",
      title: "Chain of Custody Procedures",
      parentCourse: "Investigative Techniques for Legal Aid",
      parentCourseId: "investigative-techniques",
      description: "How to preserve evidence integrity from collection to courtroom. Applies to both physical and digital evidence.",
      practiceArea: "All Practice Areas",
      duration: "30 min",
      updated: "2025-03-05",
      isNew: false,
      tags: ["evidence", "chain of custody", "investigation"],
      brightspaceUrl: "#brightspace/investigative-techniques/chain-of-custody"
    },
    {
      id: "module-statutory-interpretation",
      type: "module",
      title: "Statutory Interpretation",
      parentCourse: "Legal Research & Writing",
      parentCourseId: "legal-research-writing",
      description: "How courts read statutes — plain meaning, legislative history, canons of construction. Essential for arguing regulatory cases.",
      practiceArea: "All Practice Areas",
      duration: "40 min",
      updated: "2025-02-10",
      isNew: false,
      tags: ["statutes", "interpretation", "research", "regulatory"],
      brightspaceUrl: "#brightspace/legal-research/statutory-interpretation"
    },
    {
      id: "module-making-objections",
      type: "module",
      title: "Making & Meeting Objections",
      parentCourse: "Court Procedure & Courtroom Basics",
      parentCourseId: "court-procedure-basics",
      description: "The most common objections in legal aid practice. When to object, how to state it, and how to respond when opposing counsel objects to you.",
      practiceArea: "All Practice Areas",
      duration: "35 min",
      updated: "2025-01-30",
      isNew: false,
      tags: ["objections", "court", "evidence", "litigation", "trial"],
      brightspaceUrl: "#brightspace/court-procedure/objections"
    },
    {
      id: "module-eviction-notice-response",
      type: "module",
      title: "Responding to an Eviction Notice",
      parentCourse: "Eviction Defense: From Notice to Trial",
      parentCourseId: "housing-eviction-defense",
      description: "The first 72 hours after a client receives an eviction notice. What to file, what to tell your client, what defenses to assert.",
      practiceArea: "Housing & Tenant Rights",
      duration: "25 min",
      updated: "2025-04-20",
      isNew: true,
      tags: ["eviction", "notice", "housing", "tenant", "emergency"],
      brightspaceUrl: "#brightspace/eviction-defense/notice-response"
    },
    {
      id: "module-asylum-basics",
      type: "module",
      title: "Asylum Basics for Legal Aid Attorneys",
      parentCourse: "Immigration Removal Defense",
      parentCourseId: "immigration-removal-defense",
      description: "Core asylum law, credible fear standards, and how to prepare a client's testimony for an asylum interview or hearing.",
      practiceArea: "Immigration",
      duration: "50 min",
      updated: "2025-04-18",
      isNew: true,
      tags: ["asylum", "immigration", "credible fear", "testimony"],
      brightspaceUrl: "#brightspace/immigration-removal/asylum"
    },
    {
      id: "module-snap-appeals",
      type: "module",
      title: "SNAP Fair Hearing Procedures",
      parentCourse: "Public Benefits: SNAP, SSI & Medicaid",
      parentCourseId: "public-benefits",
      description: "Step-by-step guide to requesting and winning a SNAP fair hearing. Covers notice requirements, continuances, and burden of proof.",
      practiceArea: "Public Benefits",
      duration: "30 min",
      updated: "2025-02-28",
      isNew: false,
      tags: ["SNAP", "food stamps", "hearing", "benefits", "appeal"],
      brightspaceUrl: "#brightspace/public-benefits/snap-hearing"
    },
    {
      id: "module-custody-basics",
      type: "module",
      title: "Child Custody Basics",
      parentCourse: "Family Law for Legal Aid Attorneys",
      parentCourseId: "family-law-basics",
      description: "Legal vs. physical custody, best interests standard, modification motions, and how to present a custody case in district court.",
      practiceArea: "Family Law",
      duration: "40 min",
      updated: "2025-03-18",
      isNew: false,
      tags: ["custody", "children", "family", "best interests", "modification"],
      brightspaceUrl: "#brightspace/family-law/custody"
    }
  ]
};
